version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    hostname: mongodb
#    ports:
#      - "127.0.0.1:27017:27017" # для просмотра коллекций в mongoDB compass
    env_file:
      - ../../backend/env/dev/.env.dev.db
      - ../../backend/env/.env.collections
    volumes:
      - ../init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - mongo_data:/data/db
    networks:
      - app_network

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: backend
    image: backend_app:1.0
    ports:
     - "127.0.0.1:8000:8000"
    depends_on:
      - mongodb
    volumes:
      - resources_data:/app/resources
    networks:
      - app_network

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: frontend_app:1.0
    ports:
      - "127.0.0.1:5173:5173"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mongo_data:
  resources_data:

networks:
  app_network:
    driver: bridge
