FROM python:3.11

WORKDIR /app

COPY .  .

RUN python -m venv /.venv

RUN /.venv/bin/pip install --no-cache-dir -r requirements.txt

ENV PATH="/.venv/bin:$PATH"
ENV ENV="test"

CMD ["pytest", "./test"]