version: '3.8'

services:
  mongo:
    image: mongo:7.0
    hostname: mongodb
    env_file:
      .env
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - mongo

volumes:
  mongo-data: